export const companyIndustryOptions = [
    "Agriculture and Mining",
    "Business Services",
    "Computers and Electronics",
    "Construction",
    "Consumer Services",
    "Education",
    "Financial Services",
    "Government",
    "Healthcare, Pharmaceuticals, & Biotech",
    "Hospitality & Gastronomy",
    "Manufacturing",
    "Marketing & Advertising",
    "Media & Entertainment",
    "Non-Profit",
    "Real estate",
    "Retail",
    "Software & Internet",
    "Telecommunications",
    "Transportation and Storage",
    "Travel, Recreation & Leisure",
    "Utilities",
    "Wholesale & Distributors",
    "Other",
  ];
  
  export const employeeOptions = [
    "1-9",
    "10-24",
    "25-49",
    "50-99",
    "100-149",
    "150-199",
    "200-249",
    "250-299",
    "300-399",
    "400-499",
    "500+",
  ];
  